### ISSUE TITLE
히스토리 - redo / undo 버튼 클릭

### ISSUE THREAD

**Issue by qkrdmstlr3** [boostcamp-2020/Project08-A-Styled-Map-Admin-Tool#130]
- [x] redo 버튼 클릭 시, 한 단계 변경 후 상태로 돌아간다
- [x] undo 버튼 클릭 시, 한 단계 변경 전 상태로 돌아간다

## 논의내용
- 현재 스타일 전체를 로컬스토리지에 저장해서, 그 차이를 계산해서 가져온다. (변경)
- 이전 스타일의 차이도 같이 저장해서 계산을 없애준다(redo / undo시에는 차이를 이용, compare시에는 저장된 전체 스타일을 이용)

**Comment by Eunsol0410** [comment]
## 추가 논의내용
- Local Storage 접근의 속도 차이 및 데이터 관리를 위해서 업로드는 새로고침, 창 닫힘 시에 실행되도록 하고, redux store는 창이 열리면 모든 로그를 불러오도록 변경함
- 스토리지 용량제한이 있으니 100개의 로그 저장으로 제한함
