### ISSUE TITLE
Fewer Options - 표기 단계 조절(도로)

### ISSUE THREAD

**Issue by yyjjjj** [boostcamp-2020/Project08-A-Styled-Map-Admin-Tool#64]
- [x] 표기단계에 따라 해당 요소의 밀도가 조절된다

## 논의 내용
- 우리가 구현할 때 기존 로직을 활용하는 것이 전부 일 뿐 새로운 얻을 만한 지식이 없다고 판단하여서 우선순위를 뒤로 미룸

## 추가 논의 사항
- 상태가 없어지는 이슈 => 고급설정을 기본설정 하위로 이동
- 전체 스타일 상태 업데이트 새로운 방식이 필요? 현재는 SET을 여러번 호출하는 방식이 되야함...

**Comment by Eunsol0410** [comment]
## 추가 논의 내용
- zoom에 따라 width가 달라져서, 하나의 값으로 통일 시키는 부분의 고민이 필요함
