### ISSUE TITLE
Fewer Options - 표기 단계 조절(행정구역)

### ISSUE THREAD

**Issue by yyjjjj** [boostcamp-2020/Project08-A-Styled-Map-Admin-Tool#66]
- [x] 표기단계에 따라 해당 요소의 밀도가 조절된다

## 논의내용
- 초기에 구글을 따라서 만들었지만, 랜드마크와 / 라벨의 경계가 모호했기 때문에 따라서 둘을 하나로 통합시킴
- 우리가 구현할 때 기존 로직을 활용하는 것이 전부 일 뿐 새로운 얻을 만한 지식이 없다고 판단하여서 우선순위를 뒤로 미룸

**Comment by qkrdmstlr3** [comment]
대 - 중 - 소를 확실하게 나눌 수 있는 항목으로 변경
