### ISSUE TITLE
히스토리 기능 구현

### ISSUE THREAD

**Issue by gitgitWi** [boostcamp-2020/Project08-A-Styled-Map-Admin-Tool#73]
- [x] log display. 사용자가 변경한 스타일 관련 액션의 히스토리를 저장하고, 히스토리 버튼 클릭시 해당 내역을 보여준다.

## 논의 사항
- log 저장은 Local Storage, Redux 모두 사용
- Local Storage 사용 방식: Style 전체 상태와 액션을 모두 저장
- Undo, Redo의 경우 => Log의 액션을 이용해서 처리
- Compare의 경우 => Log의 Style 전체 상태를 이용해서 처리

**Comment by Eunsol0410** [comment]
## 추가 논의 사항
- local storage 갯수 제한이 필요함

**Comment by Eunsol0410** [comment]
## 추가 논의내용
- Local Storage 접근의 속도 차이 및 데이터 관리를 위해서 업로드는 새로고침, 창 닫힘 시에 실행되도록 하고, redux store는 창이 열리면 모든 로그를 불러오도록 변경함
- 스토리지 용량제한이 있으니 100개의 로그 저장으로 제한함
