### ISSUE TITLE
비교하기 기능 구현

### ISSUE THREAD

**Issue by gitgitWi** [boostcamp-2020/Project08-A-Styled-Map-Admin-Tool#77]
- [x] Mapbox의 compare 관련 API 활용한 UI 구현
  - [x]   조절바 움직이기 구현 (`could`)
  - [x]   비교하기 비활성화 버튼 구현
- [x] 이전 스타일과 현재 스타일 비교하기 기능 구현
- [x] 비교하기 화면인 상태에서 스타일 적용

## 추가 구현 사항
- [x] 비교하는 대상을 히스토리 목록에서 표기해주기

**Comment by Eunsol0410** [comment]
## 현재 주요 사항
- 현재 mousemove를 true로 해두면 움직이는 마우스에 따라 기존의 검색창, 버튼들이 안보이는 상태
- 화면분할 비율 고려되야함
